import { PostType } from '@/features/post/types/post.type'

export const ads: PostType[] = [
  {
    _id: '1',
    user: {
      _id: '1',
      name: 'Kasuto',
      email: 'kasuto@example.com',
      avatar: '',
      banner: '',
      role: 'user',
      createdAt: '2022-01-01T10:00:00Z',
      updatedAt: '2022-01-01T10:00:00Z',
      phoneNumber: '123-456-7890',
      address: '123 Main St',
      birthday: '1990-01-01',
      gender: 'male',
      work: 'Software Engineer',
      education: 'University of Example',
      skills: 'JavaScript, React, Node.js',
      bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget sem non ipsum faucibus consequat. Donec viverra neque non ipsum aliquet, vel bibendum ligula sagittis. Sed vel diam ut ligula maximus placerat. Integer non consectetur felis. Nulla facilisi.',
      total_follower: 12,
      nickName: '',
      password: '',
      isFollowing: false,
    },
    content: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut similique reiciendis dicta esse. Dolorum sequi laudantium, perferendis voluptates optio hic. Id unde dolorum omnis, hic eligendi aperiam excepturi doloremque facilis!`,
    file_url:
      'https://kenh14cdn.com/203336854389633024/2022/6/26/3-16562337204821522976067.jpg',
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    isLiked: false,
    total_comments: 12,
    total_likes: 12,
    isSaved: false,
    status: 'public',
  },
  {
    _id: '2',
    user: {
      _id: '2',
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: '',
      banner: '',
      role: 'user',
      createdAt: '2022-01-01T10:00:00Z',
      updatedAt: '2022-01-01T10:00:00Z',
      phoneNumber: '123-456-7890',
      address: '123 Main St',
      birthday: '1990-01-01',
      gender: 'male',
      work: 'Software Engineer',
      education: 'University of Example',
      skills: 'JavaScript, React, Node.js',
      bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget sem non ipsum faucibus consequat. Donec viverra neque non ipsum aliquet, vel bibendum ligula sagittis. Sed vel diam ut ligula maximus placerat. Integer non consectetur felis. Nulla facilisi.',
      total_follower: 12,
      nickName: '',
      password: '',
      isFollowing: false,
    },
    content: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aut similique reiciendis dicta esse. Dolorum sequi laudantium, perferendis voluptates optio hic. Id unde dolorum omnis, hic eligendi aperiam excepturi doloremque facilis!`,
    file_url:
      'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8ab86111-40c3-4c11-abf4-2c512a9b3c9d/dc57upu-d554f465-e877-4afc-89e4-b36e81bc4a9b.jpg/v1/fill/w_1024,h_613,q_75,strp/samurai_by_mattforsyth_dc57upu-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NjEzIiwicGF0aCI6IlwvZlwvOGFiODYxMTEtNDBjMy00YzExLWFiZjQtMmM1MTJhOWIzYzlkXC9kYzU3dXB1LWQ1NTRmNDY1LWU4NzctNGFmYy04OWU0LWIzNmU4MWJjNGE5Yi5qcGciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.zNPdCb1Tq4f6awluE28wQ-L8qhjM8ZrfQUYBFr-2YmY',
    createdAt: new Date().toString(),
    updatedAt: new Date().toString(),
    isLiked: false,
    total_comments: 12,
    total_likes: 12,
    isSaved: false,
    status: 'public',
  },
]
